### ISSUE TITLE
请问数据库是怎么设计的？

### ISSUE THREAD

**Issue by trainKing562** [cngege/Note#1]
求一下

**Comment by cngege** [comment]
delme里面有sql文件，导入mysql数据库中能看到表结构

**Comment by cngege** [comment]
delme里面有sql文件，导入mysql数据库中能看到表结构

**Comment by trainKing562** [comment]
万分感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月26日(周日) 晚上6:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cngege/Note] 请问数据库是怎么设计的？ (Issue #1)




 
delme里面有sql文件，导入mysql数据库中能看到表结构

**Comment by trainKing562** [comment]
目录里似乎没有找到delme，不在压缩包里面吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月26日(周日) 晚上6:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cngege/Note] 请问数据库是怎么设计的？ (Issue #1)




 
delme里面有sql文件，导入mysql数据库中能看到表结构

**Comment by cngege** [comment]
> 目录里似乎没有找到delme，不在压缩包里面吗
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年5月26日(周日) 晚上6:00 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [cngege/Note] 请问数据库是怎么设计的？ (Issue #1) delme里面有sql文件，导入mysql数据库中能看到表结构 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

![图片](https://github.com/cngege/Note/assets/28597788/49b8d714-abe7-4dce-8854-c51ef602d740)
